### ISSUE TITLE
“在 Demo 中可以找到一个例子：RXRAuthDecorator。这个例子为 Rexxar Web 发出的请求添加了登录信息。”

### ISSUE THREAD

**Issue by mario-huang** [douban/rexxar-ios#10]
并没有找到RXRAuthDecorator

**Comment by guoshao-dev** [comment]
可以看看这行代码：https://github.com/douban/rexxar-ios/blob/master/RexxarDemo/FullRXRViewController.swift#L33

它完成了添加登录信息的功能。

我待会更改一下文档。

**Comment by mario-huang** [comment]
好的。感谢~
