### ISSUE TITLE
关于route.json的使用，维护与更新的问题

### ISSUE THREAD

**Issue by raffy2010** [douban/rexxar-ios#17]
1.目前route.json的定义,是否是需要对每一个资源定义一个具体的html.
比如 1: 1.html, 2: 2.html.如果是这样，那么有多少个模型是不是route.json就需要有多少个对应的项
2.route.json面对大量的实体数量是怎么保证文件的尺寸
3.服务端的route.json在更新时，客户端怎么去处理增量更新的问题

4.在客户端已经缓存了html文件之后服务端的变更如何通知客户端清除本地缓存，
清除策略有没有具体的案例

**Comment by guoshao-dev** [comment]
1 routes.json 就是 url 和 其对应 html 文件的映射，每个 url 代表一个页面。所以，url 和 html 是一一对应的。
2 routes.json 只是一个 json 文件，即使有几百个 url 和 html 的映射，也不会太大。
3 html 的文件名中可以有一个 hash 码，hash 码根据 html 文件内容计算。这样 html 文件更新了，routes.json 中相同 url 对应的 html 文件就会变化。应用控制 routes.json 的检查时间，比如开机时。Rexxar-Container 会重新下载新资源，删除旧资源。
4 清除策略都内置在 RXRRouteManager 这个类中，可以阅读代码。

**Comment by raffy2010** [comment]
多谢解答:)

按照之前的理解，html是完整的渲染好的页面，所以说存在大量的route规则的可能
按上边的解释,html应该是一个shell页面，不包含任何内容，只有对应的js,css.加载了
html之后，再通过api去请求数据，并且渲染页面，所以说比较适合与react,ng,vue
这类型框架搭配

**Comment by guoshao-dev** [comment]
是的，Rexxar 的做法就是你所说的。我们的前端业务层代码确实也是使用 React。
