### ISSUE TITLE
为什么decorator的侦听器的canInitWithRequest方法总在containerapi的侦听器的canInitWithRequest方法之前执行

### ISSUE THREAD

**Issue by huangshiguang** [douban/rexxar-ios#27]
我发现demo里面RXRLogContainerAPI和RXRGeoContainerAPI出发时url都被改了，加入了参数。于是就引发思考，是怎么控制在发数据前就把url改掉，打断点发现，每次侦听器捕捉信号后都是decorator的侦听器先响应，随后containerapi的侦听器才响应，寻找代码，并没有发现什么地方控制了这个顺序，按照我的理解它们应该是平级的。最后我在FullRXRViewController里面找到了差异
<img width="613" alt="2016-11-11 9 10 37" src="https://cloud.githubusercontent.com/assets/15666699/20216082/75009fca-a853-11e6-8390-16142d241161.png">并且发现选中的这句代码注释掉也没有关系，多次试验发现还是那样的顺序，很费解，求解答

**Comment by daydayfree** [comment]
ContainerAPI 和 RequestInterceptor 顺序是按 NSURLProtocol 注册顺序决定的
