### ISSUE TITLE
RXRContainerAPI不支持异步处理

### ISSUE THREAD

**Issue by 2-Y** [douban/rexxar-ios#28]
RXRContainerAPI并不支持实现类控制返回responseData、NSURLResponse的时间；
比如H5获取native的通讯录；

**Comment by xujialiang** [comment]
用信号量，把异步方法 变为同步

**Comment by daydayfree** [comment]
@2-Y 可以在 RXRContainerAPI 里面，自定义 NSURLSession 做异步获取，可以参考 [这里](https://github.com/douban/rexxar-ios/blob/e4afc9b001298416a487cfd338e0ddc79c3a4a9d/Rexxar/Decorator/RXRRequestInterceptor.m#L79)
