### ISSUE TITLE
[RXRConfig setCacheEnable:NO] 所引发的问题

### ISSUE THREAD

**Issue by ruanhaojian** [douban/rexxar-ios#32]
我希望不启用缓存，来实现load网络上的任何地址（不一定是.html文件），并且发现默认缓存模式下：
* 如果.html文件脚本路径是相对路径情况下脚本会加载错误。
* 如果remote_file不是.html资源，文件保存会不正确。
所以，我重写RXRViewController后，每次都会加载原始的url，但是就出现了一些问题：
* 假如我配置remote_file="http://10.15.115.211:8081/"，containerAPI会触发可是fetch会进入catch，错误信息："{line:433,column:29}"
* 假如我配置remote_file="http://10.15.115.211:8081/index.html"，错误信息一样。
然后我尝试开启缓存，并且资源地址remote_file="http://10.15.115.211:8081/index.html"，containerAPI执行正确返回。

但是我最终还是希望不启用缓存，因为缓存无法加载remote_file="http://10.15.115.211:8081/"这样的路径，并且资源(css,js)路径必须是绝对路径。

请问知道这是什么原因？感谢回答！

**Comment by ruanhaojian** [comment]
错误信息 Error Domain=NSURLErrorDomain Code=-1003

**Comment by ruanhaojian** [comment]
已解决，containerApi接口域名，当在直接访问http/https地址时候，需使用可访问的域名（IP）,如：rexxar-container 这种会报1003错误

**Comment by guoshao-dev** [comment]
🚀
