### ISSUE TITLE
如何通过uri 配置 url 传值

### ISSUE THREAD

**Issue by zxm9988** [douban/rexxar-ios#36]
比如我要配置一个uri是 douban://order?orderid=*  
匹配url应该是  www.douban.com/bookshop/order?orderid=*
uri的值可以传递给URL么？

**Comment by guoshao-dev** [comment]
你能再说清楚一些你的需求吗？

在 rexxar 的流程中，一般这样使用 uri 中参数：
在路由表里，和 uri 对应的是一些 html 静态资源。请求这些 html 是不需要值的。
这些值，例如 orderid，可以通过 uri 传给 rexxar-web 的前端部分。前端部分通过 orderid 获取 api 数据。这样页面根据返回的不同数据做内容显示。

**Comment by zxm9988** [comment]
是这样的，只是不知道如果把uri 的值传递给rexxar-web 的前端部分，因为现在前端部分是jsp 并不是静态的页面。是否需要前端替换成rexxar-web 开发才可以？

**Comment by guoshao-dev** [comment]
rexxar 的各个部分并不相互依赖。

页面渲染使用 jsp 应该也可以。但这样部分业务逻辑就是在后端由 jsp 这样的脚本语言完成。然后，生成 html，再下载到 WebView 运行。这种用法和我们设计初衷相差挺大的。所以，在设计上没有考虑这种情况。

Rexxar 设计为 Web 端只能是运行于浏览器中的 JavaScript。

我们其实希望 html 页面是不变的。这样才可以缓存这部分资源。使得性能上可以接近原生。
