### ISSUE TITLE
wkwebview的支持有进展吗？

### ISSUE THREAD

**Issue by dustturtle** [douban/rexxar-ios#62]
据了解在iOS8+的客户端内置webview一些大厂已经使用了wk的解决方案（比如腾讯）

**Comment by bigyelow** [comment]
@daydayfree

**Comment by bigyelow** [comment]
@dustturtle 我们的 dev 分支已经完成了相关工作。目前需要在线上运行一段时间，稳定后会合到 master 分支。

**Comment by dustturtle** [comment]
期待，感谢～
