### ISSUE TITLE
请教一下除了html以外的资源的缓存方式如何实现的？

### ISSUE THREAD

**Issue by dustturtle** [douban/rexxar-ios#65]
看代码里面uri对应的是html, 比如css、js这些的缓存是怎么处理的？

**Comment by daydayfree** [comment]
加载 css 和 js 文件时，通过 CacheFileInterceptor 先缓存在本地，下次加载读本地文件。

CacheFileInterceptor 是一个 NSURLProtocol，截获所有的静态文件请求。

可以参考 [这里](https://github.com/douban/rexxar-ios/blob/master/Rexxar/Core/RXRCacheFileInterceptor.m)。

**Comment by dustturtle** [comment]
那如果这个css文件有更新，通过什么机制保证我们使用的是最新的啊？

**Comment by daydayfree** [comment]
修改 css 和 js 文件后，服务端需要重新打包发布 routes.json 文件；
这时对应的页面有新版本，客户端重新下载对应 html 文件，这时可以清理缓存；
也可以通过打包程序，将对应的 css 和 js 文件名加上版本号，CacheFileInterceptor 通过 url 来做标识。

**Comment by dustturtle** [comment]
我看demo里面的RXRCacheFileInterceptor的registerInterceptor并没有被调用，是不是意味着它没有起作用？ 
对于不同的NSURLProtocol子类，[NSURLProtocol registerClass:[self class]] 是可以被重复注册并且分别起作用的吗？

**Comment by daydayfree** [comment]
1. 额...不应该吧

2. NSURLProtocol 有注册顺序，一个请求只能被一个 NSURLProtocol 拦截。

**Comment by dustturtle** [comment]
css和js很多时候都是共用的，这个也和html绑定在一起管理吗？

**Comment by dustturtle** [comment]
还有一个不明白的地方是RXRNSURLProtocol 和  RXRCacheFileInterceptor 都是 NSURLProtocol 的子类，他们各自是怎么起作用的？

**Comment by dustturtle** [comment]
还有一个RXRContainerInterceptor是RXRNSURLProtocol 的子类

**Comment by dustturtle** [comment]
demo里面注册两次的示例：（不太理解其作用机制）
    // ContainerAPIs
    let geoContainerAPI = RXRGeoContainerAPI()
    let logContainerAPI = RXRLogContainerAPI()
    RXRContainerInterceptor.containerAPIs = [geoContainerAPI, logContainerAPI]
    let _  = RXRNSURLProtocol.registerRXRProtocolClass(RXRContainerInterceptor.self)

    // Decorators
    let headers = ["Customer-Authorization": "Bearer token"]
    let parameters = ["apikey": "apikey value"]
    let requestDecorator = RXRRequestDecorator(headers: headers, parameters: parameters)
    RXRRequestInterceptor.decorators = [requestDecorator]
    let _ = RXRNSURLProtocol.registerRXRProtocolClass(RXRRequestInterceptor.self)

**Comment by bigyelow** [comment]
@dustturtle 

1. `RXRCacheFileInterceptor` 在本地没有缓存文件的时候将从服务端请求的静态文件缓存下来 https://github.com/douban/rexxar-ios/blob/master/Rexxar/Core/RXRCacheFileInterceptor.m#L199 。可以看下 `fileHandle` 这个属性的用法；

2. `RXRContainerInterceptor` 用来模拟服务器的 api 调用，但是实际是返回本地数据；

rexxar-iOS 中有三种不同类型的 Interceptor
- `RXRRequestInterceptor`：配合 `RXRRequestDecorator` 使用，截获一般请求，用于个性化定制 request
- `RXRContainerInterceptor`：模拟 api 请求，返回本地数据
- `RXRCacheFileInterceptor`：截获静态文件请求，并将返回的文件缓存
