### ISSUE TITLE
没看懂registerRXRProtocolClass里这么写的意思

### ISSUE THREAD

**Issue by leoliuyt** [douban/rexxar-ios#68]
+ (void)_frd_setCount:(NSInteger)count forRegisteredClass:(Class)clazz
{
  NSString *key = NSStringFromClass(clazz);
  NSMutableDictionary *mutDict = [sRegisteredClassCounter mutableCopy];
  if (key) {
    if (!mutDict) {
      mutDict = [NSMutableDictionary dictionary];
    }
    mutDict[key] = @(count);
  }
}

**Comment by bigyelow** [comment]
```
+ (void)_frd_setCount:(NSInteger)count forRegisteredClass:(Class)clazz
{
  NSString *key = NSStringFromClass(clazz);
  NSMutableDictionary *mutDict = [sRegisteredClassCounter mutableCopy];
  if (key) {
    if (!mutDict) {
      mutDict = [NSMutableDictionary dictionary];
    }
    mutDict[key] = @(count);
  }
}
```
@daydayfree bug 了吧？ 
少了
```
sRegisteredClassCounter = mutDict;
```

**Comment by daydayfree** [comment]
@bigyelow 对的，逻辑有问题
