### ISSUE TITLE
0.3.0  如何解决  NSURLProtocol 截获 Post 请求时 Body 被清空的问题？

### ISSUE THREAD

**Issue by xiaolongyuan** [douban/rexxar-ios#76]
0.3.0   使用 WKWebView 替换 UIWebView, 由于 WKWebView 对 NSURLProtocol 支持不够友好，你需要特别关心一下 NSURLProtocol 截获 Post 请求时 Body 被清空的问题。

**Comment by bigyelow** [comment]
duplicated https://github.com/douban/rexxar-ios/issues/75
