### ISSUE TITLE
3.0改wkwebview后，cookie是怎么管理的？

### ISSUE THREAD

**Issue by xdonx** [douban/rexxar-ios#78]
在3.0里没有看到cookie相关代码。
我需要设置cookie（或用NSHTTPCookieStorage里的）该怎么做？因为wkwebview的创建以及request的操作都在rexxar里处理的。盼回复，谢谢。

**Comment by daydayfree** [comment]
Cookie 可以在 `RXRWebViewDelegate` 方法里面设置。

iOS9 以上可以在 `webView.configuration.websiteDataStore` 设置 cookie，低版本可以通过 `NSHTTPCookieStorage` 设置。
