### ISSUE TITLE
Web端加自定义header，客户端拦截不到

### ISSUE THREAD

**Issue by wyhazq** [douban/rexxar-ios#84]
iOS和Android都是这样，有遇到过吗？Google了一圈，都没有问这个问题的，是加Web端加header的方式不对或者是其他原因？求大神解析。

**Comment by bigyelow** [comment]
拦截不到是指在什么情况下拦截不到？
是 RXRViewController 加载 url 没有调用下面的方法吗？
```
- (BOOL)webView:(WKWebView *)webView
    shouldStartLoadWithRequest:(NSURLRequest *)request
    navigationType:(WKNavigationType)navigationType
```

**Comment by wyhazq** [comment]
没有进入这个方法，进入的是RequestInterceptor的startLoading方法，但打印header时，基本的header字段有，没有web添加的自定义header。

**Comment by bigyelow** [comment]
你需要继承 RXRRequestDecorator 方法实现自己的 Decorator 用来定制 request。

在这里 https://github.com/douban/rexxar-ios/blob/master/Rexxar/Decorator/RXRRequestInterceptor.m#L66

RequestInterceptor 会使用你的 decorator 来定制 request

**Comment by bigyelow** [comment]
这里有说明 https://github.com/douban/rexxar-ios/blob/master/Rexxar/Decorator/RXRRequestDecorator.h#L17

**Comment by wyhazq** [comment]
OK，现在就是这么解决的，谢谢。
